### ISSUE TITLE
This isn't the right place to put this but...

### ISSUE THREAD

**Issue by VhatAmI** [DustinEwers/shiny-angular-demos#2]
Not an issue, but somewhat related to the repo. 

Have you ever been able to get razor, angular-cli, and .netcore to play nicely together? 
I've been trying to get a project that uses all 3 but everything seems to fall apart when I try to add razor into the mix 

Reason I came here was because I used one of your blog posts while playing around trying to get it to work : https://dustinewers.com/angular-cli-with-net-core/

**Comment by DustinEwers** [comment]
Honestly, I'm not a big fan of using Razor with Angular. To me, Razor is a different (but not bad) way to build pages. My current preference is to use Angular and hit a web API with it. The Angular app is almost like a secondary application that's embedded within the Core App. 

In theory, you could do a Razor page and embed an Angular application on the page, but I wouldn't recommend it. Best of luck!
